apiVersion: v1
kind: Service
metadata:
  name: student-service
spec:
  selector:
    app: student
  type: NodePort  
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30005
