apiVersion: apps/v1
kind: Deployment
metadata:
  name: student-deployment
  labels:
    app: student
spec:
  replicas: 1
  selector:
    matchLabels:
      app: student
  template:
    metadata:
      labels:
        app: student
    spec:
      containers:
      - name: student
        image: dmitrys04/k8s_lab
        ports:
        - containerPort: 5000
        env:
        - name: MONGODB_CONNSTRING
          valueFrom: 
            configMapKeyRef:
              name: mongodb-configmap
              key: database_url
